Emurgo/yoroi-graphql-migration-backend

README.md

This is quickly written documentation for the endpoints. It's useful for people who are updating from v1 to v2 who need to know how it works.
I know this is not perfectly accurate since the current history endpoint doesn't match the current v2 API. Additionally, it would be much better if we could automatically generate documentation to avoid it falling out of sync. However, since this project is just meant as a temporary step to fully onboard onto GraphQL, maybe this is good enough.

Quick documentation

---

src/services/accountState.ts

Seems sometimes an empty array is returned.

Fix account state

---

src/Transactions/certificates.ts
src/services/regHistory.ts
src/services/transactionHistory.ts

requires this version of cardano-graphql https://github.com/input-output-hk/cardano-graphql/pull/285

fix - works with schema from cardano-db-sync-4.0.0

---

src/Transactions/certificates.ts
src/index.ts

Change to make the backend compatible cardano-db-sync 5.0.1.
Also a small error handling change.

renaming the pool hash id column

---

src/index.ts
tests/txHistory.test.ts

Bug was introduces here https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/68
I added a test to catch this in the future

fix rollback check on tx history query

---

.eslintrc.json
package-lock.json
package.json
src/Transactions/certificates.ts
src/index.ts
src/middleware/index.ts
src/services/poolInfo.ts
src/services/signedTransaction.ts
src/services/transactionHistory.ts
src/services/utxoForAddress.ts
tests/bestBlock.test.ts
tests/dataSingleHistory.ts
tests/healthCheck.test.ts
tests/txHistory.test.ts
tests/utxoForAddresses.test.ts
tests/utxoSumForAddresses.test.ts

This PR fixes all the eslint issues and also adds `husky` as a dependency to avoid pushing eslint issues in the future.

Fix eslint issues

---

default.nix

Enforcing the usage of node 12.

default.nix: moving to node 12

---

src/services/filterUsedAddress.ts

filterUsed: sending a set

---

README.md
src/index.ts
src/services/poolHistory.ts
src/services/poolInfo.ts

delegation history

---

src/Transactions/types.ts
src/services/transactionHistory.ts
tests/dataSingleHistory.ts
tests/txHistory.test.ts

All the tests run against mainnet, so I will add new tests once we have multi-assets in mainnet.
You can check https://explorer.cardano-testnet.iohkdev.io/en/address.html?address=addr_test1qzddgtdqxmsvn0rqp0ltdfpddudvf76qs3esyn3zqf44drkprmcgc38nvy9hu4k5dcyxhyqcdsfwnf50q5sm03x89e9slwzp5f&page=2&perPage=2
and then check that the response matches:
```
[
{
"hash": "c9f112a8f20e0cf618918f76c936e859769f02f25539c3b90844dbf6fa3d3250",
"fee": "168801",
"metadata": null,
"type": "shelley",
"withdrawals": [],
"certificates": [],
"tx_ordinal": 0,
"tx_state": "Successful",
"last_update": "2021-02-04T05:57:36.000Z",
"block_num": 2288266,
"block_hash": "eb91d8480a5d9cb5b72021347e80d2769064c29988fc55200b4c022aef08bec9",
"time": "2021-02-04T05:57:36.000Z",
"epoch": 112,
"slot": 34640,
"inputs": [
{ …
```

add mary support for 'txHistory'

---

README.md
src/Transactions/types.ts
src/services/transactionHistory.ts
src/services/utxoForAddress.ts
src/utils/index.ts

UtxoForAddresses

---

src/ws-server.ts

The websocket endpoint no longer worked so I fixed it.
Presumably the cause is that the "UTXO" view that was being reference no longer exists (presumably it was created for graphql)

Fix websocket connection

---

src/services/rewardHistory.ts

fix order for rewards query

---

src/index.ts

Just clarified the voting dates for Fund 6, it is inconsequential for us, but we show this info to the users

fixing voting dates for catalyst fund6

---

README.md
src/index.ts
src/services/multiAssetSupply.ts

this PR adds /multiAsset/supply endpoint for getting supplies for given assets

feature - add endpoint to get supplies of given multi assets

---

package-lock.json
package.json

Milestone: https://github.com/Emurgo/yoroi-graphql-migration-backend/milestone/4?closed=1
Includes schema updates for db-sync 12

Release / 2.0.0

---

.eslintrc.json

remove-linebreakstyle-from-eslint

---

benchmark.yml

Add config file for benchmarking with [https://github.com/fcsonline/drill](https://github.com/fcsonline/drill)

add-drill-benchmark-config

---

package-lock.json
package.json

Milestone: https://github.com/Emurgo/yoroi-graphql-migration-backend/milestone/5?closed=1

Release / 2.1.0

---

src/services/messageBoard.ts
src/services/messageDirect.ts
tests/getMessageBoard.test.ts
tests/getMessageDIrect.test.ts

Just a tiny bit of housekeeping to keep closer to Yoroi conventions:
* change snake_case -> camelCase
* move SQL out of handler

refactor(cip12): snake_case -> camelCase + move sql out of handler

---

package-lock.json
package.json

Milestone: https://github.com/Emurgo/yoroi-graphql-migration-backend/milestone/6?closed=1

Release / 2.2.0

---

README.md
src/Transactions/output.ts
src/Transactions/types.ts
src/Transactions/userDefinedFunctions.ts
src/Transactions/valid_utxos_view.ts
src/services/txIO.ts
src/services/utxoForAddress.ts
src/utils/mappers.ts

https://github.com/Emurgo/yoroi-graphql-migration-backend/issues/307

include data_hash in txo endpoints

---

README.md
src/index.ts
src/services/policyIdExists.ts

this PR adds a new endpoint to check if given policyIds already exist on chain

add policyIdExists endpoint

---

src/services/txStatus.ts

the endpoint was throwing error when signedTxQueueEndpoint was returning error

fix txStatus 404 error

---

package-lock.json
package.json

Milestone: https://github.com/Emurgo/yoroi-graphql-migration-backend/milestone/7?closed=1

Release / 2.3.0

---

README.md
src/index.ts

JIRA ticket: [YOMO-106](https://emurgo.atlassian.net/browse/YOMO-106)

add isQueueOnline flag

---

src/coin-price/poller.ts

This is a tmp measure to facilitate the initial deployment process.

do not run the poller unless a flag file is present

---

src/coin-price/db-api.ts
src/coin-price/model.ts
src/coin-price/poller.ts

also, run poller only on master

bug fix for price api

---

src/Transactions/certificates.ts

Rename table column of stake_address from `registered_tx_id` to `tx_id`

[YB-21] Rename registered_tx_id attribute of stake_address table to tx_id

---

src/index.ts
src/middleware/index.ts
src/middleware/utils.ts
src/utils/index.ts

Added V2.1 endpoints to the array of routes.

YB-26: Add v2.1 endpoints
