src/index.ts
Adding current backend unix time to the api status endpoint. Keep in mind this is in ms, divide by 1000 for seconds.
=> index: adding current time to /status endpoint

src/services/utxoForAddress.ts, tests/utxoForAddresses.test.ts
introduced in https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/34.
When this endpoint used graphql, hasura and co took care of the decoding.
I forgot to do this when I moved it to sql to support payment creds.
=> bugfix - decode tx_hash from the database from hex into string.

package-lock.json, package.json, src/services/accountState.ts
The latest version of serialization-lib implements CIP5 which should automatically be picking the correct bech32 prefix.
=> Bump serialization lib

src/index.ts, tests/txHistory.test.ts
the test for this is awkward, as mocha.js doesn't have great out-of-the-box
support for testing async functions this way.  We use a try-catch block
and have an always-failing test in the try block to ensure that the api
is failing correctly.
=> bugfix - txHistory endpoint errors when after tx doesn't exist.

.eslintrc.json, src/index.ts, src/services/transactionHistory.ts, src/utils/index.ts, tests/txHistory.test.ts
It looks like https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/41 broke support for querying by staking keys to get withdrawals where none of the inputs/outputs belong to the user
This PR fixes the issue and adds tests to cover this
=> fix staking key queries

src/index.ts, src/services/transactionHistory.ts, tests/txHistory.test.ts
When we paginate, we pass in two things in the "After" field
```
after: {
tx: "a5fb58900cbd0a6f5b77bac47fa950555dddb85f684a074b7a748f5b6e3b1aad",
block: "6575c26f4eb1533d2087e5e755ff0b606f4fc663a40f7aa558c38c389400f2f0"
},
```
Before this PR, the "tx" field was mostly ignored (all we did was check the tx does exist in the block). However, to support mid-block pagination, this PR makes that querying with an "After" transaction returns any tx in the block that occurs after that transaction
=> support mid-block pagination

README.md, src/Transactions/types.ts, src/services/transactionHistory.ts, tests/txHistory.test.ts
The check for the era of the transaction had a typo in it causing it to always return "shelley". This PR properly makes it return "byron" in the Byron case.
=> Fix era in transaction

src/services/transactionHistory.ts, tests/txHistory.test.ts
Previously the tx history query only returned:
- Staking key registration
- Stake delegation
- Staking key deregistration
This PR also adds Pool Registration if the reward address matches the address passed in
=> Add pool registration to reward address history

README.md, src/services/filterUsedAddress.ts, src/services/transactionHistory.ts, src/services/utxoForAddress.ts, src/services/utxoSumForAddress.ts, src/utils/index.ts, tests/filterUsedAddresses.test.ts, tests/txHistory.test.ts, tests/utxoForAddresses.test.ts
`filterUsed`, `history` and `utxoForAddresses` used to support payment keys by passing in the payment key hash directly
However, this doesn't really scale well into the future since payment keys have no particular structure (just random bytes), so there would be no way to expand our API to support any future key types. So instead, I changed all the endpoints to accept hex-encoded addresses (notably enterprise addresses) instead of raw payment keys to provide the loose matching support.
=> Rework payment key support

src/services/transactionHistory.ts, tests/txHistory.test.ts
Txs where the payment key only occurs in the output weren't recognized.
=> Fix tx history query on payment keys

src/services/accountState.ts, tests/getAccountState.test.ts
The endpoint would only return the correct result for staking keys that received ITN rewards. This PR fixes it.
=> Fix account state endpoint

README.md, src/services/filterUsedAddress.ts, src/utils/cip5.ts, src/utils/index.ts, tests/filterUsedAddresses.test.ts, tests/txHistory.test.ts, tests/utxoForAddresses.test.ts
This switches the endpoints to use [CIP5](https://github.com/cardano-foundation/CIPs/tree/master/CIP5) for both payment key queries and stake queries (we already used it for regular addresses)
For backwards compatibility, we still allow stake keys to be passed in as hex-string, but we can remove this in a future version after Yoroi Extension & Yoroi Mobile have updated.
=> Use CIP5 for queries

src/Transactions/certificates.ts, src/utils/index.ts, tests/getPoolInfo.test.ts
The `poolParamsOwners` in the history endpoint is a concatenation of all the pool owners ever (including duplicates) instead of the pool operators for the specific transaction
This PR fixes the issue. I added a test using the `STKH1` stake pool since they pool has multiple updates that also include multiple owners.
=> Fix pool owner list in certificates

src/Transactions/certificates.ts, src/services/poolInfo.ts, src/services/regHistory.ts, src/services/transactionHistory.ts, src/services/utxoForAddress.ts
This contains #98 . The only difference is that #98 was missing a conversion of `Hash32HexString` > `Hash32Hex`
=> Update to cardano-db-sync 6.0.0

src/services/transactionHistory.ts, tests/txHistory.test.ts
Adds tx metadata support based on https://github.com/input-output-hk/cardano-db-sync/pull/389
Note: the 6.0.0 release doesn't introduce the tx metadata feature. You'll need to re-sync from scratch the cardano-db-sync with latest master.
=> Add tx metadata support

src/Transactions/certificates.ts
Porting up to cardano-db-sync 7.1.0.
=> Transactions/certificates: rename pool.reward_addr_id

src/services/signedTransaction.ts
The `cardano-rest 3.1.0` is supposed to be accepting base64 as well per documentation, but it is not working as submitted in https://github.com/input-output-hk/cardano-rest/issues/109#issuecomment-744021831.
We need to convert it to hex for now.
=> services/signedTransaction: convert to hex before posting

src/services/signedTransaction.ts
This reverts commit 73e7ed3cdb662dffba393dc22fecad71b1e6d834.
This now works with the latest release ` cardano-rest 3.1.1`.
=> Revert "services/signedTransaction: convert to hex before posting"

README.md, src/services/rewardHistory.ts
add pool ids to rewards history endpoint
e.g., new response
```
{
"e1c11ef08c44f3610b7e56d46e086b90186c12e9a68f0521b7c4c72e4b": [
{
"epoch": 213,
"reward": "21200",
"poolHash": "df1750df9b2df285fcfb50f4740657a18ee3af42727d410c37b86207"
},
{
"epoch": 214,
"reward": "19533",
"poolHash": "0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735"
},
{
"epoch": 215,
"reward": "20948",
"poolHash": "0f292fcaa02b8b2f9b3c8f9fd8e0bb21abedb692a6d5058df3ef2735"
},
```
=> add pool ids to rewards history endpoint

src/services/accountState.ts
Catalyst treasury rewards were accidentally not included in the accountState query
=> Add treasury to account state

src/services/transactionHistory.ts
When removing graphql (#134), this bug was introduced
Querying a block that doesn't exist as the "untilBlock" for a tx history query should throw a `REFERENCE_BEST_BLOCK_MISMATCH` error, but instead it got `TypeError: Cannot read property 'blockNumber' of undefined`
=> Fix REFERENCE_BEST_BLOCK_MISMATCH error

src/Transactions/types.ts, src/services/transactionHistory.ts, tests/dataSingleHistory.ts, tests/txHistory.test.ts
*Note*: Asset support needs to be merged first #160 
This change should improve the speed of the txhistory endpoint by 10x (at least). We were doing some computations in the entire metadata table rather than just in the results that we needed
=> TxHistory Improvement

src/services/signedTransaction.ts
Changing the content-type as from now we are going to use `cardano-wallet` instead of `cardano-rest`.
Also adding an console output when a tx fails, so we can have the request itself for debugging.
=> signedTransaction: the new endpoint accepts binary

README.md, tests/rewardHistory.test.ts
I remove the `api` prefix in all the URLs of the documentation. This is because the `api` prefix is not something we add in our library -- it's something our backend server has configured. This should fix #111
=> Remove API prefix

.github/workflows/pr-checks.yml, src/services/accountState.ts
Fixed the rewards query to only use one latest MIR cert per address per epoch
=> [HOT] Fix rewards query

src/index.ts
1. Voting dates were wrongly pointing to a date before registration
2. Correct end of registration is Sep 30
3. Better more stable format
=> fixing catalyst dates and safer date format

src/index.ts, src/services/multiAssetTxMint.ts
This PR has the objective of adding a new endpoint to get metadata from the minting transactions for specific tokens, given their names and policy ids
We need this endpoint mainly to be able to differentiate between "normal" native tokens and native tokens which are NFTs. By getting the metadata from the transaction which minted a token, we can verify if it is a NFT by checking if the `key` returned on the response is `721`.
See the [task on Asana](https://app.asana.com/0/1200842454080452/1200880500671157).
This task is for adding a function for counting token and NFT types on the Yoroi extension. Even though we have token data on the UTXOs which we can access on the extension, the data from the UTXOs is insufficient for determining if these tokens are NFTs or not.
The implementation is …
=> Add endpoint for getting the metadata from a mint transaction

.npmrc, src/Transactions/certificates.ts, src/services/accountState.ts, src/services/poolInfo.ts, src/services/rewardHistory.ts, tests/getPoolInfo.test.ts
These changes aim to return treasury and reserves information directly from the `reward` table, as well as return the data from the new epoch columns in the reward history endpoint.
See the [task on Asana](https://app.asana.com/0/1200842454080452/1200648261290964) for more background.
There are some schema changes at `cardano-db-sync` referent to the rewards, namely, the `treasury` and `reserve` tables are no longer necessary, as their data is now being stored directly on the `reward` table. We can check whether the reward is treasury or reserve by the `type` column in the `reward` table.
The implementation consists of the following parts:
Change the `epoch_no` column to `earned_epoch` and add the new `spendable_epoch`. Also add `spendableEpoch` to the `interface` wee return and map it …
=> changes to query rewards only from reward table and use new epoch cols

src/services/signedTransaction.ts
Currently, the error response when tx submission fails is like this:
```
{"error":{"response":"Error trying to send transaction: Error: Request failed with status code 400 - [object Object]"}}
```
which is not very helpful.
This PR should make it better.
=> better error info when tx submission fails

src/Transactions/certificates.ts, src/Transactions/types.ts, src/index.ts, src/services/transactionHistory.ts
This PR includes the new columns `valid_contract` and `script_size` from `tx` table in the transactions history response. It also fixes some bugs which prevented the correct functioning of the `v2/txs/history` endpoint.
See the [task on Asana](https://app.asana.com/0/1200528935481340/1200936111290863/f)
This view is used on the query from the `v2/txs/history` endpoint and there were three bugs here, two which prevents the view from being created at all and another one which causes a runtime error (when someone actually runs a query against the view):
- in db-sync 11, the table `pool_meta_data` was renamed to `pool_metadata_ref`, **so we change the reference with the old name in this view**;
- the 4th query in the view contains a aggregate function, but it doesn't include a `group by` …
=> Include tx valid_contract and script_size fields on tx history response

src/Transactions/certificates.ts, src/Transactions/types.ts, src/index.ts, src/services/transactionHistory.ts
This PR contains changes for returning the UTxOs from collateral inputs at the `/v2/txs/history` endpoint.
In db-sync 11 it was added a new table named `collateral_tx_in`, which serves the same purpose as `tx_in` but for inputs referring collaterals for script exceution for the transaction.
See the [task on Asana](https://app.asana.com/0/1200528935481340/1200936111290864/f)
This view is used on the query from the `v2/txs/history` endpoint and there were three bugs here, two which prevents the view from being created at all and another one which causes a runtime error (when someone actually runs a query against the view):
- in db-sync 11, the table `pool_meta_data` was renamed to `pool_metadata_ref`, **so we change the reference with the old name in this view**;
- the 4th query in the view …
=> Return collateral input UTxOs at transaction history

README.md, src/index.ts, src/services/oracleDatapoint.ts, src/services/oracleTicker.ts, tests/getOracleDatapoints.test.ts, tests/getOracleTickers.test.ts
This is part of the Catalyst project funded effort to provide access to metadata oracles datapoints in Yoroi.
This PR implements:
* getting all tickers of queried oracles (their addresses)
* getting relevant datapoints with many filtering options (by ticker, by ticker&source, by block proximity or by latest data)
Thanks!!!
=> feat(oracles): add metadata oracle support

src/services/transactionHistory.ts
The data-hash querying has been added before the history handler have been critically rolled back to an older version. This PR returns the querying back into the handler but also fixed incorrect original reference, see https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/308#pullrequestreview-863573026
=> Fixing data_hash in history handler

README.md, src/index.ts, src/services/assetMintTxs.ts
This PR adds an endpoint for retrieving all mint transactions for a given asset fingerprint together with their respective metadata if it has any.
=> add asset mint txs endpoint

README.md, config/default.ts, package-lock.json, package.json, src/index.ts, src/services/validateNft.ts, src/utils/index.ts
Adds an endpoint for triggering [`Yoroi Content Validator`](https://github.com/Emurgo/yoroi-content-validator) for a given NFT fingerprint, or return the current validation results in case the validation was already performed
for testing purposes this branch was rebased to [fix/change-endpoints-to-use-multi-asset-table](https://github.com/Emurgo/yoroi-graphql-migration-backend/tree/fix/change-endpoints-to-use-multi-asset-table) #284
=> Add endpoint for NFT image validation

src/Transactions/userDefinedFunctions.ts
The bug:
```
$ curl https://iohk-mainnet.yoroiwallet.com/api/txs/io/8dd71b5a737b076fda5432b2954cdbf164a26ed892768504986d8742b7bae87d/o/0 | jq .
{
"output": {
...
"dataHash": "\\xcd7250596c2b8e7ccff79c44939195561b1f2dd6abc310345d52b43f67a21e40",
...
```
The `\\x` prefix should not be there.
=> Fix `dataHash` format error

config/default.ts, src/index.ts, src/services/transactionHistory.ts
This PR rollbacks to the original TX history query and also set `work_mem` and `max_parallel_workers` for the global `Pool`
=> Set pool configurations and rollback to 

config/default.ts, src/services/validateNft.ts
On Fibo we have more distinct environments than Yoroi, therefore we cannot rely on the env var to define which version of the Lambda should be used. The dev, QA and staging environments on Fibo interact with the testnet environment of Yoroi backend, therefore, we need this extra field in the payload to make the distinction of which Lambda to call.
=> Validate nft by env

package-lock.json, package.json, script/coin-price-data-fetcher/src/uploader.js
This is an improvement, no need for redeployment for this patch. We can merge into mater and wait for the next upgrade.
=> If price fetcher is not active, don't access the env vars

README.md, src/services/multiAssetTxMint.ts
Originally the multi-asset metadata endpoint `multiAsset/metadata` takes parameters in this form:
```
{
"assets":[
{"name":"...", "policy": "..."},
...
]
}
```
And the "name" is the asset name in hex decoded as an ASCII string.
The problem is that the blockchain protocol does not mandate the name to an ASCII string, nor even an UTF8 string. For example:
https://testnet.cardanoscan.io/tokens?pageNo=12&policyId=b940743438a9217ea9d673362f708e5080dcd7b597988ae962782e10. So a query containing a token with name like `ab6854726b0139254b7e5c4831c87ac043a938fa3543b5eb0ce0906e122083e9` leads to the PSQL error "invalid input syntax for type bytea".
This PR accepts the asset name in a hex string as the `nameHex` field.
```
{
"assets":[
{"nameHex":"...", "policy": "..."},
...
]
}
```
For …
=> multiasset info query accepts asset name in hex

src/neo4j/txs/utils.ts
Shelley time is off by -2 hours for preview
The value can be checked here: https://book.world.dev.cardano.org/environments/preview/shelley-genesis.json
```
"systemStart": "2022-10-25T00:00:00Z",
```
=> preview network shelley time fixes
